---

- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy nginx.conf
  tags: nginxconf
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify: restart nginx

- include: common-configs.yml
  tags: nginxconf

- include: site-configs.yml
  tags: nginxconf

- name: Ensure nginx cache
  file:
    path: /var/cache/nginx
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Ensure web directory is owned by www-data
  file:
    path: /var/www
    owner: www-data
    group: www-data
    state: directory
    mode: 0775

- name: Remove default nginx site config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
