---

- name: Create or update system user {{ admin_login }}
  user:
    name: "{{ admin_login }}"
    password: "{{ admin_password | password_hash('sha512') }}"
    shell: /bin/bash
    update_password: always

- name: Set {{ admin_login }}’s user directory permissions to 750
  file:
    path: /home/{{ admin_login }}
    state: directory
    mode: 0750

- name: Add authorized key to {{ admin_login }} from {{ user_key_path }}
  authorized_key:
    user: "{{ admin_login }}"
    key: "{{ lookup('file', item) }}"
    state: present
  with_items: "{{ admin_authorized_keys }}"

- name: Add {{ admin_login }} to sudoers
  lineinfile:
    create: yes
    dest: /etc/sudoers.d/10-{{ admin_login }}
    line: "{{ admin_login }} ALL=(ALL) NOPASSWD:ALL"
    state: present
    validate: visudo -cf %s

- name: Ensure {{ admin_login }} belongs to group www-data
  user:
    name: "{{ admin_login }}"
    groups: www-data
    append: yes
