---

- name: Update apt cache
  raw: apt-get update -qq

- name: Ensure python and playbook requirements are installed
  raw: test -e /usr/bin/python || apt-get install -y -qq python python-setuptools

- name: Install aptitude
  raw: apt-get install -y -qq aptitude
