---

- name: Common playbook
  hosts: all
  become: yes

  roles:

    - role: bootstrap
      tags: bootstrap

    - role: letsencrypt
      tags: letsencrypt

    - role: nginx
      tags: nginx

    - role: docker
      tags: docker
