---

- name: Common playbook
  hosts: all
  become: yes

  roles:

    - role: bootstrap
      tags: bootstrap

    - role: acme-sh
      tags: acme-sh

    - role: nginx
      tags: nginx

    - role: docker
      tags: docker
