---

- name: Reboot system
  shell: sleep 2 && shutdown -r now "Ansible triggered reboot"
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot == "yes"

- name: Waiting for system to come back
  become: false
  local_action:
    module: wait_for
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 1
    timeout: 300
  when: reboot == "yes"
